/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9f6f5",
        "inverse-surface": "#0e0e0e",
        "on-surface-variant": "#5c5b5b",
        "error-dim": "#b92902",
        "on-surface": "#2f2f2f",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#520c00",
        "secondary-dim": "#8b3315",
        "tertiary-container": "#a8a9f9",
        "surface-container-high": "#e4e2e1",
        "surface-container-low": "#f3f0f0",
        "surface-container": "#eae8e7",
        "on-secondary-container": "#802b0d",
        "on-primary-fixed-variant": "#4d674a",
        "surface-bright": "#f9f6f5",
        "tertiary-fixed": "#a8a9f9",
        "on-primary-fixed": "#324b2f",
        "surface-variant": "#dedcdc",
        "tertiary": "#53549d",
        "primary-fixed": "#d5f3ce",
        "primary": "#486245",
        "on-primary": "#ddfbd5",
        "primary-dim": "#3c563a",
        "on-tertiary-fixed-variant": "#303078",
        "error": "#b02500",
        "primary-container": "#d5f3ce",
        "surface-tint": "#486245",
        "primary-fixed-dim": "#c7e5c0",
        "tertiary-fixed-dim": "#9b9ceb",
        "surface-dim": "#d6d4d4",
        "on-secondary-fixed": "#651900",
        "on-tertiary-container": "#27276f",
        "on-secondary": "#ffefeb",
        "error-container": "#f95630",
        "on-tertiary-fixed": "#0b0757",
        "secondary-container": "#ffc4b3",
        "outline-variant": "#aeadac",
        "secondary": "#9b3e20",
        "on-tertiary": "#f4f1ff",
        "secondary-fixed": "#ffc4b3",
        "surface-container-highest": "#dedcdc",
        "tertiary-dim": "#464890",
        "inverse-on-surface": "#9e9c9c",
        "on-secondary-fixed-variant": "#8d3416",
        "secondary-fixed-dim": "#ffb199",
        "on-primary-container": "#435d40",
        "on-background": "#2f2f2f",
        "on-error": "#ffefec",
        "outline": "#777676",
        "inverse-primary": "#e0ffd9",
        "background": "#f9f6f5"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
